export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";

export const GET_PDODUCT_REQUEST = "GET_PDODUCT_REQUEST";
export const GET_PDODUCT_SUCCESS = "GET_PDODUCT_SUCCESS";
export const GET_PDODUCT_FAILURE = "GET_PDODUCT_FAILURE";