export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const DELETE_USERS_FAILURE = "DELETE_USERS_FAILURE";

export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS";
export const ADD_USERS_FAILURE = "ADD_USERS_FAILURE";

export const EDIT_USERS_SUCCESS = "EDIT_USERS_SUCCESS";
export const EDIT_USERS_FAILURE = "EDIT_USERS_FAILURE";

export const SINGLE_USERS_SUCCESS = "SINGLE_USERS_SUCCESS";
export const SINGLE_USERS_FAILURE = "SINGLE_USERS_FAILURE";

export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS";
export const SEARCH_USERS_FAILURE = "SEARCH_USERS_FAILURE";

export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAILURE = "ADD_CART_FAILURE";

export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAILURE = "DELETE_CART_FAILURE";

export const ADD_BILL_SUCCESS = "ADD_BILL_SUCCESS";
export const ADD_BILL_FAILURE = "ADD_BILL_FAILURE";

export const GET_BILL_SUCCESS = "GET_BILL_SUCCESS";
export const GET_BILL_FAILURE = "GET_BILL_FAILURE";

export const GET_SINGLE_BILL_SUCCESS = "GET_SINGLE_BILL_SUCCESS";


export const EDIT_BILL_SUCCESS = "EDIT_BILL_SUCCESS";

export const DELETE_BILL_SUCCESS = "DELETE_BILL_SUCCESS";

